(let ((key-mappings
       '(("C-x w" kill-this-buffer)
         ("C-c /" comment-region)
         ("C-c ;" uncomment-region)
         ("C-<f5>" global-display-line-numbers-mode)
         ("<f6>" slime)
         ("<C-f6>" slime-quit-lisp)
         ("C-c C--" shrink-window)
         ("C-c C-+" enlarge-window)
         ("C-c C-=" enlarge-window)
         ("C-x C-b" ibuffer)
         ("C-c <up>" windmove-up)
         ("C-c <down>" windmove-down)
         ("C-c <left>" windmove-left)
         ("C-c <right>" windmove-right))))
  (dolist (mapping key-mappings)
    (global-set-key (kbd (pop mapping)) (pop mapping))))

;;(windmove-default-keybindings)
